#!/bin/bash

if [ -z "$SRCROOT" ]
then
    export SRCROOT=`pwd`
fi

if [ -z "$CACHEROOT" ]
then
	export CACHEROOT="$SRCROOT/Carthage Cache"
fi

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "LD = $SRCROOT/scripts/ld.py" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

export CARTHAGE="$SRCROOT/Carthage"
rm -rf "$CARTHAGE"
carthage update --platform iOS --no-use-binaries
export CARTHAGE_SHA=`$SRCROOT/scripts/carthage_sha`
echo "CARTHAGE_SHA is $CARTHAGE_SHA"
echo $CARTHAGE_SHA > "$SRCROOT/Cartfile.hash"
export CARTHAGE_CACHE="$CACHEROOT/$CARTHAGE_SHA"
echo "CARTHAGE_CACHE is $CARTHAGE_CACHE"
mv "$SRCROOT/Cartfile.hash" "$CARTHAGE/Cartfile.hash"
if [ -d "$CARTHAGE" ] && [ ! -d "$CARTHAGE_CACHE" ]
then
	mkdir -p "$CACHEROOT/"
	cp -R "$CARTHAGE" "$CARTHAGE_CACHE"
fi