#!/bin/bash

if [ -z "$SRCROOT" ]
then
    export SRCROOT=`pwd`
fi

if [ -z "$CACHEROOT" ]
then
	export CACHEROOT="$SRCROOT/Carthage Cache"
fi

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "LD = $SRCROOT/scripts/ld.py" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

export CARTHAGE="$SRCROOT/Carthage"
export CARTHAGE_SHA=`"$SRCROOT/scripts/carthage_sha"`
export CARTHAGE_CACHE="$CACHEROOT/$CARTHAGE_SHA"

if [ "$1" == "force" ]
then
	echo "Removing prebuilt dependencies..."
	rm -rf "$CARTHAGE"
	rm -rf "$CARTHAGE_CACHE"
fi

echo $CARTHAGE_SHA > "$SRCROOT/Cartfile.hash"
if ! cmp -s "$SRCROOT/Cartfile.hash" "$CARTHAGE/Cartfile.hash"
then
	rm -rf "$CARTHAGE"
	if [ -d "$CARTHAGE_CACHE" ] && [ ! -d "$CARTHAGE" ]
	then
		cp -R "$CARTHAGE_CACHE" "$CARTHAGE"
	else
		brew upgrade carthage 2> /dev/null
		carthage bootstrap --platform iOS --no-use-binaries 2> /dev/null
		mv "$SRCROOT/Cartfile.hash" "$CARTHAGE/Cartfile.hash"
		if [ -d "$CARTHAGE" ] && [ ! -d "$CARTHAGE_CACHE" ]
		then
			mkdir -p "$CACHEROOT/"
			cp -R "$CARTHAGE" "$CARTHAGE_CACHE"
		fi
	fi
else
	rm "$SRCROOT/Cartfile.hash"
fi